# Ejercicio de edades e ingresos


*   Generar una matriz de 3*3 de edades entre 20 y 50 años
*   Generar una matriz de 3*3 de ingresos entre 2000 y 5000 miles de pesos
*   Unir la data uno a uno en una matriz 9 * 2
*   Filtrar aquellas filas cuya edad esta entre 20 y 30 años y cuyos ingresos estan entre 2000 y 5000









---



1. Generar una matriz de 3*3 de edades entre 20 y 50 años

In [100]:
import numpy as np
print(np.__version__)

1.21.6


In [101]:
mis_edades_aleatoreas = np.random.uniform(

low=20,
high=50,
size= (3,3),


)
redondear= np.round(mis_edades_aleatoreas)

redondear

array([[38., 25., 38.],
       [25., 46., 36.],
       [47., 23., 20.]])

 2. Generar una matriz de 3*3 de ingresos entre 2000 y 5000 miles de pesos

In [102]:
mis_ingresos_aleatoreas = np.random.uniform(

low=2000,
high=5000,
size= (3,3),


)
redondear_ingresos= np.round(mis_ingresos_aleatoreas)

redondear_ingresos

array([[2473., 2674., 2237.],
       [3195., 3426., 4780.],
       [3838., 2205., 4031.]])

3. Unir la data uno a uno en una matriz 9 * 2

In [103]:
filtro_1 = redondear_ingresos.reshape (9,1)
filtro_1

array([[2473.],
       [2674.],
       [2237.],
       [3195.],
       [3426.],
       [4780.],
       [3838.],
       [2205.],
       [4031.]])

In [104]:
filtro_2 = redondear.reshape (9,1)
filtro_2

array([[38.],
       [25.],
       [38.],
       [25.],
       [46.],
       [36.],
       [47.],
       [23.],
       [20.]])

In [105]:

a = filtro_1
b = filtro_2
ab=np.column_stack((a,b))
display(
    a,
    b,
    ab
    
)

array([[2473.],
       [2674.],
       [2237.],
       [3195.],
       [3426.],
       [4780.],
       [3838.],
       [2205.],
       [4031.]])

array([[38.],
       [25.],
       [38.],
       [25.],
       [46.],
       [36.],
       [47.],
       [23.],
       [20.]])

array([[2473.,   38.],
       [2674.,   25.],
       [2237.,   38.],
       [3195.,   25.],
       [3426.,   46.],
       [4780.,   36.],
       [3838.,   47.],
       [2205.,   23.],
       [4031.,   20.]])


4. Filtrar aquellas filas cuya edad esta entre 20 y 30 años y cuyos ingresos estan entre 2000 y 5000



a.Filtrar aquellas filas cuyos ingresos estan entre 2000 y 5000

In [119]:
print (a)
for e in a:
  print (3000<=e<=5000)

[[2473.]
 [2674.]
 [2237.]
 [3195.]
 [3426.]
 [4780.]
 [3838.]
 [2205.]
 [4031.]]
[False]
[False]
[False]
[False]
[False]
[ True]
[False]
[False]
[ True]



b. Filtrar aquellas filas cuya edad esta entre 20 y 30 años

In [107]:
print (b)
for e in b:
  print (20<=e<=30)

[[38.]
 [25.]
 [38.]
 [25.]
 [46.]
 [36.]
 [47.]
 [23.]
 [20.]]
[False]
[ True]
[False]
[ True]
[False]
[False]
[False]
[ True]
[ True]


In [117]:
print (a)
for e in a:
  filtro_ingreso = print (2000<=e<=5000)

print (b)
for f in b:
  filtro_edad=print (20<=f<=30)
display(
np.logical_and (e,f)
)


[[2473.]
 [2674.]
 [2237.]
 [3195.]
 [3426.]
 [4780.]
 [3838.]
 [2205.]
 [4031.]]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[[38.]
 [25.]
 [38.]
 [25.]
 [46.]
 [36.]
 [47.]
 [23.]
 [20.]]
[False]
[ True]
[False]
[ True]
[False]
[False]
[False]
[ True]
[ True]


array([ True])